services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: digital_hunter
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql


  phpmyadmin:
    image: phpmyadmin
    ports: 
    - 8080:80
    restart: always
    links: 
    - mysql
    environment:
      PMA_ARBITRARY: 1
    depends_on:
      - mysql



volumes:
  mysql_data:
